development:
  adapter: postgresql
  encoding: unicode
  database: waywt_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: waywt_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: waywt_production
  pool: 5
  username:
  password:
